# Machine Learning Assignment 3: Classification

In [13]:
# Libraries for working with data
import pandas as pd
import numpy as np

# Dataset
from sklearn.datasets import load_breast_cancer

# Splitting and preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Classification models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# Model evaluation
from sklearn.metrics import accuracy_score

In [14]:
# Load the Breast Cancer Wisconsin dataset
cancer = load_breast_cancer()

# Convert the feature data into a pandas DataFrame
df = pd.DataFrame(
    cancer.data,
    columns=cancer.feature_names
)

# Add the target column
df["target"] = cancer.target

# Display the first five rows
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0


## Dataset Inspection

In [15]:
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Dataset shape: (569, 31)

Column names:
['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension', 'radius error', 'texture error', 'perimeter error', 'area error', 'smoothness error', 'compactness error', 'concavity error', 'concave points error', 'symmetry error', 'fractal dimension error', 'worst radius', 'worst texture', 'worst perimeter', 'worst area', 'worst smoothness', 'worst compactness', 'worst concavity', 'worst concave points', 'worst symmetry', 'worst fractal dimension', 'target']

Data types:
mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
target                       int64
dtype: object

Missing values:
mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

Duplicate rows:
0

In [16]:
# Count malignant and benign cases
class_counts = df["target"].value_counts().sort_index()

class_distribution = pd.DataFrame({
    "Target": [0, 1],
    "Diagnosis": ["Malignant", "Benign"],
    "Count": [class_counts[0], class_counts[1]]
})

class_distribution

   Target  Diagnosis  Count
0       0  Malignant    212
1       1     Benign    357

## Separating Features and Target

In [17]:
# Independent variables: all 30 measurements
X = df.drop("target", axis=1)

# Target variable: tumour diagnosis
y = df["target"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (569, 30)
Target shape: (569,)

## Train-Test Split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training feature shape:", X_train.shape)
print("Testing feature shape:", X_test.shape)
print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

Training feature shape: (455, 30)
Testing feature shape: (114, 30)
Training target shape: (455,)
Testing target shape: (114,)

## Feature Scaling

In [19]:
# Create the StandardScaler
scaler = StandardScaler()

# Learn the mean and standard deviation from the training data
X_train_scaled = scaler.fit_transform(X_train)

# Apply the same transformation to the testing data
X_test_scaled = scaler.transform(X_test)

print("Feature scaling completed.")
print("Training data shape:", X_train_scaled.shape)
print("Testing data shape:", X_test_scaled.shape)

Feature scaling completed.
Training data shape: (455, 30)
Testing data shape: (114, 30)

## 2. Classification Algorithms

### 1. Logistic Regression


### 2. Decision Tree Classifier

### 3. Random Forest Classifier

### 4. Support Vector Machine

### 5. k-Nearest Neighbors

In [20]:
# Create the five required classification models
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=5000,
        random_state=42
    ),

    "Decision Tree": DecisionTreeClassifier(
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    ),

    "Support Vector Machine": SVC(),

    "k-Nearest Neighbors": KNeighborsClassifier(
        n_neighbors=5
    )
}

print("All five classification models were created successfully.")

All five classification models were created successfully.

## 3. Model Training and Evaluation

In [21]:
# Empty list for storing model results
results = []

# Empty dictionary for storing model predictions
predictions = {}

# Train and evaluate each classification model
for model_name, model in models.items():

    # Train the model
    model.fit(X_train_scaled, y_train)

    # Predict the diagnoses for the test data
    y_pred = model.predict(X_test_scaled)

    # Save the predictions
    predictions[model_name] = y_pred

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Store the model result
    results.append({
        "Model": model_name,
        "Accuracy": accuracy
    })

    # Display the accuracy
    print(model_name)
    print("Accuracy:", round(accuracy, 4))
    print("-" * 40)

Logistic Regression
Accuracy: 0.9825
----------------------------------------
Decision Tree
Accuracy: 0.9123
----------------------------------------
Random Forest
Accuracy: 0.9561
----------------------------------------
Support Vector Machine
Accuracy: 0.9825
----------------------------------------
k-Nearest Neighbors
Accuracy: 0.9561
----------------------------------------

In [22]:
# Convert the model results into a DataFrame
results_df = pd.DataFrame(results)

# Sort from highest to lowest accuracy
results_df = results_df.sort_values(
    by="Accuracy",
    ascending=False
).reset_index(drop=True)

# Convert accuracy into percentage form
results_df["Accuracy Percentage"] = (
    results_df["Accuracy"] * 100
).round(2)

# Round the original accuracy column
results_df["Accuracy"] = results_df["Accuracy"].round(4)

results_df

                    Model  Accuracy  Accuracy Percentage
0     Logistic Regression    0.9825                98.25
1  Support Vector Machine    0.9825                98.25
2           Random Forest    0.9561                95.61
3     k-Nearest Neighbors    0.9561                95.61
4           Decision Tree    0.9123                91.23

In [23]:
# First row has the highest accuracy
best_model = results_df.iloc[0]

# Last row has the lowest accuracy
worst_model = results_df.iloc[-1]

print("BEST-PERFORMING MODEL")
print("Model:", best_model["Model"])
print("Accuracy:", best_model["Accuracy"])
print("Accuracy Percentage:", best_model["Accuracy Percentage"], "%")

print("\nWORST-PERFORMING MODEL")
print("Model:", worst_model["Model"])
print("Accuracy:", worst_model["Accuracy"])
print("Accuracy Percentage:", worst_model["Accuracy Percentage"], "%")

BEST-PERFORMING MODEL
Model: Logistic Regression
Accuracy: 0.9825
Accuracy Percentage: 98.25 %

WORST-PERFORMING MODEL
Model: Decision Tree
Accuracy: 0.9123
Accuracy Percentage: 91.23 %

## Model Comparison

The five classification algorithms were evaluated using accuracy on 114 test observations.


Model	Accuracy	Accuracy Percentage
0	Logistic Regression	0.9825	98.25
1	Support Vector Machine	0.9825	98.25
2	Random Forest	0.9561	95.61
3	k-Nearest Neighbors	0.9561	95.61
4	Decision Tree	0.9123	91.23



### Best-Performing Algorithms

Logistic Regression and Support Vector Machine were the joint
best-performing algorithms. Both models achieved an accuracy of 98.25%,
correctly classifying 112 of the 114 test observations.


### Worst-Performing Algorithm

Decision Tree was the worst-performing algorithm, with an accuracy of
91.23%. It correctly classified 104 of the 114 test observations.

A single decision tree can create highly specific rules from the training
data. This may cause overfitting, where the tree learns the training data
closely but performs less accurately on new observations.

## Conclusion

This project implemented and compared five supervised machine-learning
classification algorithms using the Breast Cancer Wisconsin dataset.

The preprocessing process included:

- Converting the dataset into a pandas DataFrame
- Inspecting the data
- Checking missing values and duplicate rows
- Examining the class distribution
- Separating features and target
- Creating stratified training and testing sets
- Standardizing the numerical features

The models were compared using classification accuracy.